debug-mode: false    #Print debug information in the console

#             Messages to display to staff members when their shift starts or ends             #
################################################################################################

shift-end-afk-message: "&4Your shift has been automatically ended because you went afk! Hours This Month: %stafftimesheet_current-hours%. Your Monthly Goal: %stafftimesheet_time-goal%."
shift-end-clockout-message: "&a Shift ended. Your time has been logged! Hours This Month: %stafftimesheet_current-logged-time%. Your Monthly Goal: %stafftimesheet_time-goal%."
shift-start-message: "&aYour shift has started. Your time is being logged!"




#                         Shift end labels for use in the staff logbooks                       #
################################################################################################

shift-start-label: "[&aClocked In]"
shift-end-label-afk: "[&4AFK]"
shift-end-label-disconnected: "[&4Disconnected]"
shift-end-label-clockout: "[&4Clocked Out]"
shift-end-plugin-disabled: "[&4Plugin Disabled]"




#                                         Error Messages                                       #
################################################################################################

error-message-negative-time: "&4Removing this much time will cause this staff member to have negative hours! Please don't remove more time than this staff member has already logged."
error-message-not-staff: "&4You are not part of the staff members list!"  #Displayed to the player if they attempt /staff shift start but they are not configured under the 'staff-members' section of the config
error-message-not-clocked-in: "&4You are not currently clocked in!"       #Displayed if a player tries to use /staff shift end but they are not currently on the clock
error-message-staff-member-does-not-exist: "&4No staff member exists with that name!"
