debug-mode: false       #Print debug information in the console

billing-period-duration: 4       #(Default: 4 weeks) The number of weeks that are in the log cycle. Current logged hours of staff members resets after this amount of time.
                        #Log cycle reports are generated at the end of the log cycle

first-bill-period-start-date: "2016/10/01"   #Start date for the first bill cycle (format: yyyy/mm/dd)

#             Messages to display to staff members when their shift starts or ends             #
#                                                                                              #
#                   These messages will evaluate the following placeholders:                   #
#   %stafftimesheet_current-logged-time% => Time staff member logged in this billing period    #
#     %stafftimesheet_time-goal% => Time goal for the staff member in this billing period      #
################################################################################################

shift-start-stop-messages:
  shift-end-afk: "&cYour shift has been automatically ended because you went afk! Hours This Month: %stafftimesheet_current-logged-time%. Your Monthly Goal: %stafftimesheet_time-goal%."
  shift-end-clockout: "&aShift ended. Your time has been logged! \nHours This Month: %stafftimesheet_current-logged-time%. \nYour Monthly Goal: %stafftimesheet_time-goal%. \nProgress: %stafftimesheet_percent-time-logged%"
  shift-start: "&aYour shift has started. Your time is being logged!"
  shift-start-return-from-afk: "&aYou have been automatically clocked in after returning from being afk!"




#                                  Command Result Messages                                     #
#                                                                                              #
#   These messages are displayed to the command invoker as a result of a command being run     #
################################################################################################

command-result-messages:
  reset-staff-member-logged-time: "&aLogged time has been reset for this staff member."      #Message displayed after command /staff manage <player_name> reset is successfully executed
  add-logged-time-for-staff-member: "&aSuccessfully added time for staff member."            #Message displayed after command /staff manage <player_name> add <formatted_time> is successfully executed 
  subtract-logged-time-for-staff-member: "&aSuccessfully subtracted time for staff member."  #Message displayed after command /staff manage <player_name> subtract <formatted_time> is successfully executed                             #Message displayed after command /staff logbook <player_name> <start_date> [end_date] is successfully executed and the command invoker is given the logbook




#                           Staff Member Logbook Configuration                                 #
################################################################################################

event-labels:
  shift-start: "[&aClocked In&r]"                        #Text to log when the staff member starts their shift
  shift-start-return-from-afk: "[&aReturned from Afk&r]" #Text to log when the staff member comes back from being afk
  shift-end-afk: "[&4AFK&r]"                             #Text to log when the staff member goes AFK
  shift-end-disconnected: "[&4Disconnected&r]"           #Text to log when the staff member disconnects from the server
  shift-end-clockout: "[&4Clocked Out&r]"                #Text to log when the staff member clocks out
  shift-end-plugin-disabled: "[&4Plugin Disabled&r]"     #Text to log when the plugin is disabled




#                                         Error Messages                                       #
################################################################################################

error-messages:
  duration-underflow: "&cYou cannot remove more time than the staff member has logged!"     #Error message displayed if a super admin tries to remove more time from a staff member than they have currently logged.
  duration-overflow: "&cYou added too much time! Max allowed time: 99:59:59"                #Error message displayed if a super admin tries to add more time to a staff member's time than the max duration value
  not-staff: "&cYou are not a staff member!"                                                #Error message displayed to the player if they attempt /staff shift start but they are not configured in staff-members.yml
  not-clocked-in: "&cYou are not currently clocked in!"                                     #Error message displayed if a player tries to use /staff shift end but they are not currently on the clock
  already-clocked-in: "&cYou are already clocked in!"                                       #Error message displayed if the player tries to clock in if they are already clocked in
  staff-member-does-not-exist: "&4No staff member exists with that name!"                   #Error message displayed when an a staff command is run with a player name that doesn't belong to any staff member
  no-staff-log: "&cCouldn't find any logs for that staff member!"                           #Error message displayed when the plugin is unable to load a staff member's logs
  invalid-duration-format: "&cInvalid duration format. Please use format: hh:mm:ss"         #Error message displayed when an invalid duration format is entered from the user 
  invalid-date-format: "&cInvalid date format. Please use format: yyyy/mm/dd"               #Error message displayed when an invalid date format is entered from the user
  start-date-end-date-mismatch: "&cYou entered a start date that comes after the end date!" #Error message displayed when the user enters a range of dates in a command but the start date comes after the end date