name: StaffTimesheet
main: com.antarescraft.kloudy.stafftimesheet.StaffTimesheet
version: 1.3.1
author: Kloudy
website: www.antarescraft.com

depend: [Essentials, HoloGUIApi]

commands:
  staff:
    description: used to define commands for the StaffTimesheet plugin
    aliases: [st, stafftimesheet]

permissions:
  staff.*:
    default: op
    description: Gives the staff member access to all commands and features
    children:
      staff.admin: true
      staff.shift: true

  staff.admin:
    description: Gives the staff member access to shift admin commands
    default: op

  staff.shift:
    description: Gives the player the ability to use shift commands
    default: op