name: StaffTimesheet
main: com.antarescraft.kloudy.stafftimesheet.StaffTimesheet
version: 1.1
author: Kloudy
website: www.antarescraft.com

depend: [Essentials, PermissionsEx, HoloGUIApi]

commands:
  staff:
    description: used to define commands for the StaffTimesheet plugin

permissions:
  staff.*:
    description: Gives the staff member access to all commands and features
    children:
      hg.admin: true
      hg.see: true
      hg.stationary: true

  staff.admin:
    description: Gives the staff member access to shift admin commands
    default: op

  staff.shift:
    description: Gives the player the ability to use shift commands
    default: true