package com.antarescraft.kloudy.stafftimesheet.config;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;

import com.antarescraft.kloudy.hologuiapi.plugincore.config.BooleanConfigProperty;
import com.antarescraft.kloudy.hologuiapi.plugincore.config.ConfigElement;
import com.antarescraft.kloudy.hologuiapi.plugincore.config.ConfigParser;
import com.antarescraft.kloudy.hologuiapi.plugincore.config.ConfigProperty;
import com.antarescraft.kloudy.hologuiapi.plugincore.config.ConfigurationParseException;
import com.antarescraft.kloudy.hologuiapi.plugincore.config.IntConfigProperty;
import com.antarescraft.kloudy.hologuiapi.plugincore.exceptions.InvalidDateFormatException;
import com.antarescraft.kloudy.hologuiapi.plugincore.messaging.MessageManager;
import com.antarescraft.kloudy.hologuiapi.plugincore.time.TimeFormat;
import com.antarescraft.kloudy.stafftimesheet.BillingPeriod;
import com.antarescraft.kloudy.stafftimesheet.StaffTimesheet;

import org.bukkit.Bukkit;

import org.bukkit.configuration.file.YamlConfiguration;

import net.md_5.bungee.api.ChatColor;

/**
 * Contains all configuration data for StaffTimesheet
 * 
 * This class is instantiated populated by the ConfigParser library
 */
public class StaffTimesheetConfig
{	
	private static StaffTimesheet staffTimesheetPlugin;
	
	private StaffTimesheetConfig() throws ConfigurationParseException, IOException
	{
		File staffMembersYml = new File(String.format("plugins/%s/staff-members.yml", StaffTimesheet.pluginName));
		YamlConfiguration staffYaml = YamlConfiguration.loadConfiguration(staffMembersYml);
		
		staffMemberManager = ConfigParser.parse(staffYaml, StaffMemberManager.class,
				String.format("plugins/%s/autogenerated-staff-members-config-docs.yml", StaffTimesheet.pluginName), 45);
	
		File billingPeriodHistoryYml = new File(String.format("plugins/%s/billing-period-history.yml", StaffTimesheet.pluginName));
		YamlConfiguration billingPeriodHistoryYaml = YamlConfiguration.loadConfiguration(billingPeriodHistoryYml);
		
		billingPeriodHistory = ConfigParser.parse(billingPeriodHistoryYaml, BillingPeriodHistory.class, 
				String.format("plugins/%s/autogenerated-billing-period-history.yml", StaffTimesheet.pluginName), 45);
	}
	
	private StaffMemberManager staffMemberManager;
	
	private BillingPeriodHistory billingPeriodHistory;
	
	@ConfigElement
	@ConfigProperty(key = "error-messages", note = "List of error messages")
	private ErrorMessages errorMessages;
	
	@ConfigElement
	@ConfigProperty(key = "event-labels", note = "List of event labels that get displayed in a staff member's logbook")
	private EventLabels eventLabels;
	
	@ConfigElement
	@ConfigProperty(key = "shift-start-stop-messages", note = "List of messages that get displayed to staff members when the start or stop their shift")
	private ShiftStartStopMessages shiftStartStopMessages;
	
	@ConfigElement
	@ConfigProperty(key = "command-result-messages", note = "List of messages displayed to the player after running a StaffTimesheet command")
	private CommandResultMessages commandResultMessages;
	
	@BooleanConfigProperty(defaultValue = false)
	@ConfigProperty(key = "debug-mode", note = "Print debug information in the console")
	private boolean debugMode;
	
	@IntConfigProperty(defaultValue = 4, maxValue = Integer.MAX_VALUE, minValue = 0)
	@ConfigProperty(key = "billing-period-duration", note = "")
	private int billingPeriodDuration;
	
	@ConfigProperty(key = "first-bill-period-start-date", note = "Start date for the first bill cycle (format: yyyy/mm/dd)")
	private String firstBillPeriodStartDate;
		
	private String setFormattingCodes(String text)
	{
		return ChatColor.translateAlternateColorCodes('&', text);
	}
	
	public static void writePropertyToConfigFile(String yamlRelativeFilePath, String path, Object value)
	{
		try
		{	
			File configFile = new File("plugins/" + staffTimesheetPlugin.getName() + "/" + yamlRelativeFilePath);
			YamlConfiguration yaml = YamlConfiguration.loadConfiguration(configFile);
			yaml.set(path, value);
			yaml.save(configFile);

		}catch(Exception e){
			MessageManager.error(Bukkit.getConsoleSender(),
				String.format("[%s]Error saving values to the config file. Does the file still exist?", staffTimesheetPlugin.getName()));}
	}

	/*
	 * Getter Functions
	 */
	
	public StaffMemberManager getStaffMemberManager()
	{
		return staffMemberManager;
	}
	
	public EventLabels getEventLabels()
	{
		return eventLabels;
	}
	
	public ErrorMessages getErrorMessages()
	{
		return errorMessages;
	}
	
	public CommandResultMessages getCommandResultMessage()
	{
		return commandResultMessages;
	}
	
	public BillingPeriodHistory getBillingPeriodHistory()
	{
		return billingPeriodHistory;
	}
	
	public int getBillingPeriodDuration()
	{
		return billingPeriodDuration;
	}
	
	public Calendar getFirstBillPeriodStartDate()
	{	
		Calendar date = null;
		try 
		{
			date = TimeFormat.parseDateFormat(firstBillPeriodStartDate);
		} catch (InvalidDateFormatException e) {}
		
		if(date == null)
		{
			MessageManager.error(Bukkit.getConsoleSender(), "Invalid Config Value: current-bill-period-start-date");
		}
		
		return date;
	}
	
	private BillingPeriod generateFirstBillingPeriod()
	{
		return new BillingPeriod(getFirstBillPeriodStartDate(), getBillingPeriodDuration());
	}
	
	public BillingPeriod getCurrentBillingPeriod()
	{
		ArrayList<BillingPeriod> billingPeriods = billingPeriodHistory.getAllBillingPeriodHistory();
		if(billingPeriods.size() == 0)
		{
			billingPeriods.add(generateFirstBillingPeriod());
		}
		
		return billingPeriods.get(billingPeriods.size()-1);//the last billing period in the list will be the current billing period
	}
}